-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 15:09:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_avozes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_avozes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_avozes` DEFAULT CHARACTER SET utf8 ;
USE `db_avozes` ;

-- -----------------------------------------------------
-- Table `db_avozes`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_avozes`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_avozes`.`TAB_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_avozes`.`TAB_PRODUTO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NULL,
  `NASCIMENTO` DATE NULL,
  `GENERO` VARCHAR(255) NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `VALOR` DECIMAL(8,2) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_avozes`.`TAB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_avozes`.`TAB_USUARIO` (
  `ID` BIGINT NOT NULL,
  `NOME` VARCHAR(255) NULL,
  `USUARIO` VARCHAR(255) NULL,
  `SENHA` VARCHAR(255) NULL,
  `FOTO` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_avozes`.`TAB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_avozes`.`TAB_CATEGORIA` (
  `ID` BIGINT NOT NULL,
  `TIPO_DE_CONSELHO` VARCHAR(255) NULL,
  `PRODUTO_ID` BIGINT NULL,
  `USUARIO_ID` BIGINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TAB_CATEGORIA_TAB_PRODUTO_idx` (`PRODUTO_ID` ASC) VISIBLE,
  INDEX `fk_TAB_CATEGORIA_TAB_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TAB_CATEGORIA_TAB_PRODUTO`
    FOREIGN KEY (`PRODUTO_ID`)
    REFERENCES `db_avozes`.`TAB_PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAB_CATEGORIA_TAB_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `db_avozes`.`TAB_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
